"""
GitHub MCP Server

Creates a feature branch and pull request for each migrated module.
Requires GITHUB_TOKEN and GITHUB_REPO in .env.

Falls back gracefully if credentials are not configured.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from config import Config
from utils.logger import get_logger

logger = get_logger("mcp.github")


class GitHubServer:
    def __init__(self):
        self._available = False
        if not Config.GITHUB_TOKEN or not Config.GITHUB_REPO:
            logger.warning("GitHub credentials not configured — PR creation disabled.")
            return
        try:
            from github import Github, GithubException

            self._gh = Github(Config.GITHUB_TOKEN)
            self._repo = self._gh.get_repo(Config.GITHUB_REPO)
            self._GithubException = GithubException
            self._available = True
            logger.info(f"GitHub connected → {Config.GITHUB_REPO}")
        except Exception as exc:
            logger.warning(f"GitHub unavailable. ({exc})")

    # ── Public API ────────────────────────────────────────────────────────────

    def create_pr(
        self,
        module_name: str,
        python_file_path: Path,
        python_code: str,
        test_results_summary: str,
    ) -> Optional[str]:
        """Commit the migrated file on a feature branch and open a PR. Returns PR URL."""
        if not self._available:
            return None

        branch = f"migration/{module_name.lower().replace(' ', '-')}"
        try:
            base = self._repo.get_branch("main")
            try:
                self._repo.create_git_ref(f"refs/heads/{branch}", base.commit.sha)
            except self._GithubException:
                pass  # branch already exists

            rel_path = f"src/{python_file_path.name}"
            try:
                existing = self._repo.get_contents(rel_path, ref=branch)
                self._repo.update_file(
                    rel_path,
                    f"chore: update {module_name} migration",
                    python_code,
                    existing.sha,
                    branch=branch,
                )
            except self._GithubException:
                self._repo.create_file(
                    rel_path,
                    f"feat: migrate {module_name} VB → Python",
                    python_code,
                    branch=branch,
                )

            pr = self._repo.create_pull(
                title=f"[Migration] {module_name}: VB → Python",
                body=self._pr_body(module_name, test_results_summary),
                head=branch,
                base="main",
            )
            logger.info(f"PR created: {pr.html_url}")
            return pr.html_url

        except Exception as exc:
            logger.error(f"GitHub PR creation failed: {exc}")
            return None

    # ── Private ───────────────────────────────────────────────────────────────

    def _pr_body(self, module_name: str, test_summary: str) -> str:
        return f"""## Migration: {module_name}

Automated VB → Python migration via the Migration Orchestrator pipeline.

### Pipeline Steps Completed
- [x] Step 1 — Discovery, Documentation & Architecture
- [x] Step 2 — Test-Driven Development (Functional + Golden Master)
- [x] Step 3 — Conversion & Closed-Loop Execution

### Test Results
```
{test_summary}
```

---
*Generated by VB → Python Migration Orchestrator*
"""
